### ISSUE TITLE
pls support width and height  animate

### ISSUE THREAD

**Issue by ariesjia** [bendc/animateplus#14]
can you and width and height in `supportedCSSprops`

**Comment by samosale** [comment]
You can use `Scale` for that.

**Comment by ariesjia** [comment]
I want animate height only , so Scale is not suitable for this scenario

**Comment by rizqinizamil** [comment]
How about `scaleY`?

**Comment by samosale** [comment]
`scale(1,2)` to animate height double its size. Although they do not produce exactly the same output as expected.

**Comment by ariesjia** [comment]
if we have background  img , set `scale` will deformed

**Comment by bendc** [comment]
Animate Plus only allows you to animate cheap CSS properties in order to avoid choppy animations. So, unless browsers eventually find a way to make `width` and `height` as inexpensive as `transform`, Animate Plus won't support them.

That being said, there are many ways to simulate a `height` animation, the most popular one being the "sliding doors" technique. Here's a [basic example](http://sharedfil.es/ouBWYVuuVK.html).
